// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<footer class=\"relative z-30 flex flex-col md:flex-row justify-evenly md:items-start p-4 md:p-12 bg-primary color-secondary\"><div class=\"flex-1 mb-4 md:mb-0\"><label class=\"text-xl md:text-4xl font-bold\">GoWeb Template</label><p class=\"text-lg md:text-xl\">A template for developing web apps with golang.</p></div><div class=\"flex-1 flex md:justify-around text-md md:text-lg\"><div class=\"mr-12 md:mr-0\"><h1 class=\"font-bold mb-2\">STACK</h1><ul><li><a href=\"https://go.dev/\" class=\"hover:underline\">Golang</a></li><li><a href=\"https://templ.guide/\" class=\"hover:underline\">Templ</a></li><li><a href=\"https://tailwindcss.com/\" class=\"hover:underline\">Tailwind</a></li><li><a href=\"https://htmx.org/\" class=\"hover:underline\">HTMX</a></li><li><a href=\"https://docs.gofiber.io/\" class=\"hover:underline\">Fiber</a></li><li><a href=\"https://github.com/jackc/pgx\" class=\"hover:underline\">Postgres</a></li></ul></div><div><h1 class=\"font-bold mb-2\">About</h1><ul><li><a href=\"https://github.com/mmoehabb/goweb-template\" class=\"hover:underline\">Github Repository</a></li><li><a href=\"https://moehab.surge.sh/\" class=\"hover:underline\">Developer</a></li></ul></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
